my_events/my_events/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
from django.conf import settings

import mydata

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mydata.urls')),
]
if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(
            settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

my_events/mydata/urls.py
from django.urls import path
from . import views

app_name = 'mydata'

urlpatterns = [
    path('', views.index, name='mydata'),
    path('<int:event_id>/', views.event_detail, name='event_detail'),
    path('<int:event_id>/update', views.event_update, name='event_update'),
    path("create", views.event_create, name="event_create"),
]

my_events/mydata/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.utils import timezone

# Create your models here.
class Event(models.Model):
    name=models.CharField(max_length=200)
    description=models.TextField()
    starts_at=models.DateTimeField(default=timezone.now)
    ends_at=models.DateField(validators=[MinValueValidator(limit_value=timezone.now().date())])
    created_at=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return (
            f"{self.name}"
            f"{self.description }"
            f"({self.starts_at: %Y-%m-%d %H:%M}):"
        )

my_events/mydata/views.py
from django.shortcuts import render
from django.http import HttpResponse
from mydata.models import Event
# Create your views here.

def index(request):

    data = {
        "events": Event.objects.all()
    }

    #add template name here
    return render(request, "mydata/index.html", data)

def event_detail(request, event_id):
    event = Event.objects.get(pk=event_id)
    if not event:
        HttpResponse("Event not found or doesn't exist")
    data = {
        "my_event": event
    }

    return render(request, "mydata/detail.html", data)

def event_create(request):
   # update_event = Event.objects.get(pk=event_id)

    if request.method == "POST":
        try:
            new_event = Event()
            new_event.name = request.POST['name']
            new_event.description = request.POST['description']
            #if new_event.full_clean():
            new_event.save()
            return HttpResponse("New Event created!!")
            return HttpResponse("Something went wrong while creating event")
        except:
            return HttpResponse("Error creating new event")
        

    data = {
            "update_event": None,
            "create_or_update": True
        }
    
    return render(request, "mydata/form.html")

def event_update(request, event_id):
    update_event = Event.objects.get(pk=event_id)

    if request.method == "POST":
        try:
            update_event.name = request.POST['name']
            update_event.description = request.POST['description']
            #if new_event.full_clean():

            update_event.save()
            return HttpResponse("New Event created!!")
        except:
            return HttpResponse("Error creating new event")
        

    data = {
            "update_event": update_event,
            "create_or_update": False
        }
    
    return render(request, "mydata/form.html")

def event_form():
    pass

my_events/mydata/templates/mydata/base.html
{% load static %}
{% extends 'index.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>

    <!-- Linking the CSS file -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />



    <!-- Linking the icon of the page -->
    <link rel="icon" href="{% static 'images/plan.jpg' %}">
</head>
<body>
    <nav id="body-nav">
        <img src="{% static '' %}" alt="My image">

    </nav>
    

    <main id="body-main">

    </main>



    <footer id="body-footer">
 
    </footer>
    {% block content %}
</body>
</html>

my_events/mydata/templates/mydata/create.html
{% extends "mydata/index.html" %} {% load static %} {% block title %}
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %} {% endblock title %}
    <link href="{% static '/css/style.css' %}" rel="stylesheet" />
</head>
<body>
    <nav id="body-nav">

    </nav>
    <main id="body-main">
        <h2>Create New Event</h2>

        <form action="{% url 'mydata:event_create' %}" method="POST">

            {% csrf_token %}
            <label>Name</label>
            <input id="name" name="name" placeholder="Name" type="text" />
            <br>
            <label>Description</label>
            <input id="description" name="description" placeholder="Description" type="text" />
            <br>
            <button type="submit">Create Event</button>


    </main>
    <footer id="body-footer">


    </footer>
    {% endblock %}
</body>
</html>

my_events/mydata/templates/mydata/detail.html
{% extends "mydata/index.html" %} {% load static %} {% block title %}


    <title>My Event Page</title>

    {% endblock title %}
    <link href="{% static '/css/style.css' %}" rel="stylesheet" />
</head>
<body>
    <nav id="body-nav">

    </nav>
    <main id="body-main">
        <h1>{{ my_event.name }}</h1>
        <h3>{{ my_event.starts_at }}</h3>
        <h3>{{ my_event.ends_at }}</h3>
        <h3>{{ my_event.created_at }}</h3>
        <p>{{ my_event.description }}</p>

        <hr>
        <a href="{% url 'mydata:event_update' my_event.id %}"><button>Update Event</button></a>

    </main>
    <footer id="body-footer">


    </footer>
    
</body>
</html>

my_events/mydata/templates/mydata/form.html
{% extends "mydata/index.html" %} {% load static %}

{% block title %}
    <title>Update Event</title>

{% endblock title %}

    {% block content %}
    <main>
        <h2>
            Update Event
        </h2>

        <form method="POST">
            {% csrf_token %}


            {% if create_update is event_update %}
            <input type="hidden" name="id">
            
            Name: <br>

            <input type="name" name="name" placeholder="Name" required><br>
             <br><br>

            Description: <br>
            <p class="update_description">{{ my_event.description }}</p>
            <input type="description" name="description" placeholder="Description" required><br>
            <br><br>
            <button type="submit">Submit</button>
{% endif %}

    </main>
    {% endblock content %}

my_events/mydata/templates/mydata/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="{% static '/css/style.css' %}" rel="stylesheet" />
    <link rel="icon" href="{% static 'images/plan.jpg' %}">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css' />

   {% block title %} <title> My Event Page </title>{% endblock title %}
</head>


<body>
    <nav class="body-nav">
        <ul>
            <li><a href="base.html">Home</a></li>
            <li><a href="#">Events</a></li>
            <li><a href="#">My Profile</a></li>
        </ul>
    </nav>
    <main class="body-main">
        <section class="head-index">
        <div class="elfsight-app-9b7243ec-9c52-4f54-ae72-5b750436e106"></div>
                <iframe src="https://calendar.google.com/calendar/embed?src=59ec981e3ca9d9d03d44b7035ead238abe2573e27dbf64a690355aeef44cf873%40group.calendar.google.com&ctz=Africa%2FNairobi" style="border: 5px" width="400" height="400" frameborder="2rem" scrolling="yes"></iframe>

        <h1>Your event Calendar</h1>

        
        <ul>

            {% for e in events %}
            <li><a href="{{ e.id }}">{{ e.name }}</a></li>
            <li<a href="{{ e.id }}">Starts at: ({{ e.starts_at }})</a></li>
            <li<a href="{{ e.id }}">Ends at: ({{ e.ends_at }})</a></li>
            {% endfor %}
        </ul>
        </section>
        <section class="index-content">
            {% block content %} {% endblock content %}
        </section>
    </main>
    <footer class="body-footer">
<script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js'></script>
    </footer>
    
</body>
</html>